"""empty message

Revision ID: 1b32fd9657e7
Revises: 9055e3211769
Create Date: 2022-07-20 17:59:51.183143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b32fd9657e7'
down_revision = '9055e3211769'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('egitmen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('title', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=140), nullable=False),
    sa.Column('content', sa.String(length=140), nullable=False),
    sa.Column('facebook', sa.String(length=45), nullable=True),
    sa.Column('twitter', sa.String(length=45), nullable=True),
    sa.Column('instagram', sa.String(length=45), nullable=True),
    sa.Column('linkedin', sa.String(length=45), nullable=True),
    sa.Column('image', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('egitmen')
    # ### end Alembic commands ###
