"""empty message

Revision ID: 2fcd1ab7d8c0
Revises: 8aaea710b47d
Create Date: 2022-06-30 23:36:44.219945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fcd1ab7d8c0'
down_revision = '8aaea710b47d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('show', sa.Boolean(), nullable=True))
    op.drop_column('course', 'show_in_home')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('show_in_home', sa.BOOLEAN(), nullable=True))
    op.drop_column('course', 'show')
    # ### end Alembic commands ###
