"""empty message

Revision ID: 5957786d064f
Revises: 2fcd1ab7d8c0
Create Date: 2022-07-01 16:36:39.131207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5957786d064f'
down_revision = '2fcd1ab7d8c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('test', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'test')
    # ### end Alembic commands ###
