"""empty message

Revision ID: 68c0b9d0389b
Revises: 8a30b644fe48
Create Date: 2022-07-02 04:45:30.987648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c0b9d0389b'
down_revision = '8a30b644fe48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_history', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_history', 'created_date')
    # ### end Alembic commands ###
