"""empty message

Revision ID: 8aaea710b47d
Revises: 182f57ff1e06
Create Date: 2022-06-30 23:35:21.771604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aaea710b47d'
down_revision = '182f57ff1e06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('show_in_home', sa.Boolean(), nullable=True))
    op.drop_column('course', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('time', sa.DATETIME(), nullable=False))
    op.drop_column('course', 'show_in_home')
    # ### end Alembic commands ###
