"""empty message

Revision ID: daeef0a0d2c9
Revises: 5957786d064f
Create Date: 2022-07-01 16:36:57.844668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daeef0a0d2c9'
down_revision = '5957786d064f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('test', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###
